# Generated by Django 3.1.6 on 2021-03-13 14:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', editable=False, max_length=20)),
                ('source_video', models.TextField(default='', editable=False, max_length=4096)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('pub_date', models.DateTimeField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Instruction', max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoObj',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_video', models.CharField(default='', editable=False, max_length=20)),
                ('codec', models.CharField(default='', editable=False, max_length=10)),
                ('frame_rate', models.IntegerField(default=0, editable=False)),
                ('crf', models.CharField(default='', editable=False, max_length=10)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('ongoing', models.BooleanField(default=False, editable=False)),
                ('qp_count', models.IntegerField(default=0, editable=False)),
                ('decisions', models.TextField(default='', editable=False, max_length=4096)),
                ('user_record', models.TextField(default='', editable=False, max_length=4096)),
                ('is_fihished', models.BooleanField(default=False, editable=False)),
                ('curr_user', models.CharField(default='', editable=False, max_length=20)),
                ('user_start_date', models.DateTimeField(blank=True, editable=False)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoJnd.experiment')),
            ],
        ),
    ]
