# Generated by Django 3.1.6 on 2021-04-10 16:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Consent Form', editable=False, max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('euid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='', max_length=4096)),
                ('has_created_videos', models.BooleanField(default=False, editable=False)),
                ('configuration', jsonfield.fields.JSONField(default={'CODEC': ['264', '266'], 'CRF': ['05', '12'], 'FRAME_RATE': {'24': ['105', '111', '173'], '30': ['001', '006', '015', '089', '121', '135', '155']}, 'QP_TRIAL_NUM': 3, 'RATING_PER_SRC': 2, 'SRC_NAME': ['001', '006', '015', '089', '121', '135', '155', '105', '111', '173'], 'SRC_VIDEO_NUM': 10, 'URL_POSTFIX': 'JND_{codec}_640x480/SRC{src_name}_640x480_{frame_rate}/crf_{crf}/videoSRC{src_name}_640x480_{frame_rate}_qp_00_{qp}_{side}_crf_{crf}.mp4', 'URL_PREFIX': 'https://datasets.vqa.mmsp-kn.de/JND_datasets/Video_JND_dataset/', 'VIDEO_NUM_PER_HIT': 2})),
                ('pub_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Instruction', editable=False, max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='InterfaceText', editable=False, max_length=20)),
                ('question', models.TextField(default='', max_length=4096)),
                ('text_end_exp', ckeditor.fields.RichTextField(default='')),
                ('text_end_hit', ckeditor.fields.RichTextField(default='')),
                ('timeout_msg', models.TextField(default='', max_length=4096)),
                ('btn_text_end_hit', models.TextField(default='', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='VideoObj',
            fields=[
                ('vuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_video', models.CharField(default='', editable=False, max_length=20)),
                ('codec', models.CharField(default='', editable=False, max_length=10)),
                ('frame_rate', models.IntegerField(default=0, editable=False)),
                ('crf', models.CharField(default='', editable=False, max_length=10)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('ongoing', models.BooleanField(default=False, editable=False)),
                ('qp_count', models.IntegerField(default=0, editable=False)),
                ('qp', models.TextField(blank=True, editable=False, max_length=4096, null=True)),
                ('result_orig', models.TextField(blank=True, editable=False, max_length=4096, null=True)),
                ('result_code', models.TextField(blank=True, editable=False, max_length=4096, null=True)),
                ('is_finished', models.BooleanField(default=False, editable=False)),
                ('cur_participant', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('cur_participant_uid', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('participant_start_date', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoJnd.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('puid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', editable=False, max_length=20)),
                ('email', models.EmailField(blank=True, default='', editable=False, max_length=30, null=True)),
                ('start_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('videos', models.TextField(default='', editable=False, max_length=4096)),
                ('ongoing', models.BooleanField(default=False, editable=False)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoJnd.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auid', models.UUIDField(blank=True, editable=False, null=True)),
                ('pname', models.CharField(editable=False, max_length=20)),
                ('puid', models.CharField(editable=False, max_length=64)),
                ('result', models.TextField(default='', editable=False, max_length=4096)),
                ('submit_time', models.DateTimeField(auto_now=True, null=True)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoJnd.experiment')),
            ],
        ),
    ]
