# Generated by Django 3.1.6 on 2021-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='result',
            field=models.TextField(default='', editable=False, max_length=40960),
        ),
    ]
