# Generated by Django 3.1.6 on 2021-03-09 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoObj',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_name', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('ongoing', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('codec', models.CharField(default='', max_length=10)),
                ('decisions', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='pub_date',
        ),
    ]
