# Generated by Django 3.1.6 on 2021-04-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0002_auto_20210410_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetext',
            name='instruction_btn_text',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
