# Generated by Django 3.1.6 on 2021-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0002_auto_20210309_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoobj',
            name='exp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='videoobj',
            name='user_record',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='videoobj',
            name='decisions',
            field=models.TextField(default='', max_length=4096),
        ),
    ]
