# Generated by Django 3.1.6 on 2021-04-14 14:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0003_interfacetext_instruction_btn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='calibration',
            field=models.TextField(default='', editable=False, max_length=40960),
        ),
        migrations.AddField(
            model_name='assignment',
            name='operation_system',
            field=models.TextField(default='', editable=False, max_length=40960),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='configuration',
            field=jsonfield.fields.JSONField(default={'CODEC': ['264', '266'], 'CRF': ['05', '12'], 'FRAME_RATE': {'24': ['105', '111', '173'], '30': ['001', '006', '015', '089', '121', '135', '155']}, 'MAX_VIDEO_NUM_PER_HIT': 2, 'QP_TRIAL_NUM': 3, 'RATING_PER_SRC': 2, 'SRC_NAME': ['001', '006', '015', '089', '121', '135', '155', '105', '111', '173'], 'SRC_VIDEO_NUM': 10, 'URL_POSTFIX': 'JND_{codec}_640x480/SRC{src_name}_640x480_{frame_rate}/crf_{crf}/videoSRC{src_name}_640x480_{frame_rate}_qp_00_{qp}_{side}_crf_{crf}.mp4', 'URL_PREFIX': 'https://datasets.vqa.mmsp-kn.de/JND_datasets/Video_JND_dataset/'}),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='instruction_btn_text',
            field=models.CharField(default='', max_length=20),
        ),
    ]
