# Generated by Django 3.1.6 on 2021-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0004_auto_20210414_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='email',
            field=models.EmailField(default='', editable=False, max_length=30),
        ),
    ]
