# Generated by Django 3.1.6 on 2021-04-14 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0005_assignment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetext',
            name='no_available_exp',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
