# Generated by Django 3.1.6 on 2021-03-09 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0005_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='pub_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='source_video',
            field=models.TextField(default='', editable=False, max_length=4096),
        ),
    ]
