# Generated by Django 3.1.6 on 2021-03-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0006_auto_20210309_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoobj',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoJnd.experiment'),
        ),
    ]
