# Generated by Django 3.1.6 on 2021-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0007_auto_20210309_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoobj',
            name='exp',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
