# Generated by Django 3.1.6 on 2021-03-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0009_auto_20210309_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoobj',
            old_name='count',
            new_name='qp_count',
        ),
    ]
