# Generated by Django 3.1.6 on 2021-05-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0011_auto_20210510_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoobj',
            name='participant_start_date',
        ),
    ]
