# Generated by Django 3.1.6 on 2021-05-10 16:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0012_remove_videoobj_participant_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetext',
            name='expire_msg',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='configuration',
            field=jsonfield.fields.JSONField(default={'CODEC': ['264', '266'], 'CRF': ['05', '12'], 'FRAME_RATE': {'24': ['105', '111', '173'], '30': ['001', '006', '015', '089', '121', '135', '155']}, 'MAX_VIDEO_NUM_PER_HIT': 5, 'QP_TRIAL_NUM': 10, 'RATING_PER_SRC': 2, 'SRC_NAME': ['001', '006', '015', '089', '121', '135', '155', '105', '111', '173'], 'SRC_VIDEO_NUM': 10, 'URL_POSTFIX': 'JND_{codec}_640x480/SRC{src_name}_640x480_{frame_rate}/crf_{crf}/videoSRC{src_name}_640x480_{frame_rate}_qp_00_{qp}_{side}_crf_{crf}.mp4', 'URL_PREFIX': 'https://jnd.mmsp-kn.de/static/videos/Video_JND_dataset/'}),
        ),
    ]
