# Generated by Django 3.1.6 on 2021-05-10 18:54

import ckeditor.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videoJnd', '0013_auto_20210510_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='configuration',
            field=jsonfield.fields.JSONField(default={'CODEC': ['264', '266'], 'CRF': ['05', '12'], 'FRAME_RATE': {'24': ['105', '111', '173'], '30': ['001', '006', '015', '089', '121', '135', '155']}, 'MAX_VIDEO_NUM_PER_HIT': 5, 'QP_TRIAL_NUM': 10, 'RATING_PER_SRC': 2, 'SRC_NAME': ['001', '006', '015', '089', '121', '135', '155', '105', '111', '173'], 'SRC_VIDEO_NUM': 10, 'URL_POSTFIX': 'JND_{codec}_640x480/SRC{src_name}_640x480_{frame_rate}/crf_{crf}/videoSRC{src_name}_640x480_{frame_rate}_qp_00_{qp}_{side}_crf_{crf}.mp4', 'URL_PREFIX': './static/videos/Video_JND_dataset/'}),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='btn_text_end_hit',
            field=models.TextField(default='', max_length=4096, verbose_name='Text of the button when the HIT is done'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='expire_msg',
            field=models.TextField(default='', max_length=4096, verbose_name='When the HIT is expired, display'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='instruction_btn_text',
            field=models.CharField(default='', max_length=20, verbose_name='Text of the button in the instruction page'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='no_available_exp',
            field=ckeditor.fields.RichTextField(default='', verbose_name='When there is no experiment available, display'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='question',
            field=models.TextField(default='', max_length=4096, verbose_name='Question of the task'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='text_end_exp',
            field=ckeditor.fields.RichTextField(default='', verbose_name='When the experiment is done, display'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='text_end_hit',
            field=ckeditor.fields.RichTextField(default='', verbose_name='When the HIT is done, display'),
        ),
        migrations.AlterField(
            model_name='interfacetext',
            name='timeout_msg',
            field=models.TextField(default='', max_length=4096, verbose_name="When user doesn't make a decision, display"),
        ),
    ]
